# Generated by Django 4.2.dev20221224201622 on 2023-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
